name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        run: |
          #1 Используем плагин compose, который уже есть на ubuntu-latest в GitHub Actions
          docker compose build
          docker compose push

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |
            # Переходим в папку проекта (создай её заранее, если нет)
            mkdir -p ~/projects/node-micro-practice
            cd ~/projects/node-micro-practice

            # Если папка пустая - клонируем, если нет - подтягиваем изменения
            if [ ! -d ".git" ]; then
              git clone https://github.com/timaZhuk/NodeJS-microservises-deploy-Test-CICD.git .
            else
              git pull origin main
            fi

            # Авторизуемся в Docker, чтобы стянуть новые приватные образы
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            # Экспортируем секреты в переменные окружения сессии
            echo "MONGO_URI=${{ secrets.MONGO_URI }}" > .env
            echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> .env
            echo "RABBITMQ_URL=${{ secrets.RABBITMQ_URL }}" >> .env
            echo "REDIS_URL=${{ secrets.REDIS_URL }}" >> .env
            echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> .env
            echo "PORT=${{ secrets.API_GATEWAY_PORT }}" >> .env
            echo "IDENTITY_SERVICE_URL=${{ secrets.IDENTITY_SERVICE_URL }}" >> .env
            echo "IDENTITY_SERVICE_PORT=${{ secrets.IDENTITY_SERVICE_PORT }}" >> .env
            echo "POST_SERVICE_URL=${{ secrets.POST_SERVICE_URL }}" >> .env
            echo "POST_SERVICE_PORT=${{ secrets.POST_SERVICE_PORT }}" >> .env
            echo "MEDIA_SERVICE_URL=${{ secrets.MEDIA_SERVICE_URL }}" >> .env
            echo "MEDIA_SERVICE_PORT=${{ secrets.MEDIA_SERVICE_PORT }}" >> .env
            echo "SEARCH_SERVICE_URL=${{ secrets.SEARCH_SERVICE_URL }}" >> .env
            echo "SEARCH_SERVICE_PORT=${{ secrets.SEARCH_SERVICE_PORT }}" >> .env
            echo "CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}" >> .env
            echo "CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}" >> .env
            echo "CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}" >> .env






            # Перезапуск сервисов 
            #docker compose pull
            docker compose down
            docker compose up -d

            # Очистка старых ненужных образов (чтобы t3.micro не забился)
            docker image prune -f
